language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
before_install: gem update bundler
secure: "HhY47FjvNswMrv+rYXkEoX3aHoYJM1v4vN/v3WBRJaBaV5QejOJMICwMnekWItKKd0z46mKdjMC+t471NFf99jj7nOfE8pQ+Zx3DHymKVcuYzfwe5sUKP/4kTBwSQhYp1FS2idJ3Hbt4qzZGnHiteycJfdVtWbJuU6Z95/+sDCqRpO7SZn5Y5pmRwQzey0+xoJhxRlxQikhJix7Ne6XB6DMT53jDC+xNSW0KqMXo5O/i4gfVlQ3qpp/xuNFiUj5Nn930OjkjMNqnvKrhwEg2UZgDuztOwgDAWjZAQhBtd/yKb8MgK//Z09MwmEg5+yfgmpqhHPvmiOMLHX7xEuuZgPRDt40tkC4K90v0u8D8lW6zHAjQ5xtaLRBksgC0j9sXzw4wvXaMvkjZ1V6Br4XFxnXnXiaF2asL8L+W9PAQ6XSlNOYNLK4eEK9XUwQG2Vw7v9KG+e1AcvWfoAjJSuFLtV09+eHylkGtpnP34zo8Ci0UkpeIVIG1BMHJjzsM/Bb2PoKvRkn6BQEpVx9AV8BcWhLj/WyqSb8Sk506GFTJUm7ERUsOgrJoNFI74JEECvoMM8WPxNd9fE55U4j3OtRNxtVmuBg96Ax2t5neTilBl4LB7EuDivsyhbbt5o2SNdXCFToqN8+EJR/REUvBtGUf7d1KqjakZyB3u9epjQYYTPE="
