require 'restore_bundled_with/restore_from_repository/error'
require 'restore_bundled_with/restore_from_repository/target_file'
require 'restore_bundled_with/restore_from_repository/repository'

module RestoreFromRepository
end
